# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-05 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunker', models.CharField(max_length=20)),
                ('bunkee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_bunker', models.IntegerField(default=0)),
                ('times_bunked', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
