# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-05 17:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bunk',
            old_name='bunkee',
            new_name='bunkee_name',
        ),
        migrations.RenameField(
            model_name='bunk',
            old_name='bunker',
            new_name='bunker_name',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='times_bunker',
            new_name='bunks_performed',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='times_bunked',
            new_name='time_bunked_on',
        ),
    ]
