# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-05 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0003_auto_20190605_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
