# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0004_auto_20190605_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunk',
            name='bunkee_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bunk',
            name='bunker_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
