# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-05 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0007_auto_20190605_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='bunks_performed',
        ),
        migrations.RemoveField(
            model_name='person',
            name='times_bunked_on',
        ),
    ]
