# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-06-06 20:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bunk', '0008_auto_20190605_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunk',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 6, 20, 42, 2, 192737, tzinfo=utc)),
        ),
    ]
